In [1]:
# pytorch版本
import torch
print(torch.__version__)

2.2.1


# torch.mul
> torch.mul(a, b)：对位相乘，可以广播

该函数可以处理两种情况
1. a是向量，b是标量
2. a、b都是向量，对位相乘，可以广播

In [7]:
# 对位相成
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
print(torch.mul(a, b))

c=torch.tensor([[1,2,3],[4,5,6]])
d=torch.tensor([[4,5,6]])
print(torch.mul(c,d))

tensor([ 4, 10, 18])
tensor([[ 4, 10, 18],
        [16, 25, 36]])


# torch.mm
> 处理二维矩阵乘法，而且只能处理二维矩阵乘法，其他维度需要用torch.matmul

In [11]:
mat1=torch.randn(64,786)
mat2=torch.randn(786,10)
result=torch.mm(mat1, mat2)
print(result.shape)

torch.Size([64, 10])


# torch.bmm
> 加上了batch计算，不能广播

mat1和mat2的第一个维度为batch size，必须一致

In [17]:
mat1=torch.randn(64, 28, 32)
mat2=torch.randn(64, 32, 10)
result=torch.bmm(mat1, mat2)
print(result.shape)

torch.Size([64, 28, 10])


# torch.matmul
> 适用范围最广，能处理batch计算，能广播

In [21]:
# 向量1*向量2，则对位相乘并相加，结果是标量
tensor1=torch.tensor([1,2,3])
tensor2=torch.tensor([4,5,6])

result=torch.matmul(tensor1, tensor2)
print(result)
print(result.shape)

tensor(32)
torch.Size([])


In [24]:
# 矩阵*矩阵
tensor1=torch.randn(3, 4)
tensor2=torch.randn(4, 5)
result=torch.matmul(tensor1, tensor2)
print(result.shape)

torch.Size([3, 5])


In [23]:
# batch矩阵*batch矩阵
tensor1=torch.randn(10, 3, 4)
tensor2=torch.randn(10, 4, 5)
result=torch.matmul(tensor1, tensor2)
print(result.shape)

torch.Size([10, 3, 5])


In [26]:
# 广播
## 矩阵*向量
tensor1=torch.tensor([ [1,2,3], [4,5,6] ])
tensor2=torch.tensor([7,8,9])
result=torch.matmul(tensor1, tensor2)
print(tensor1.shape)
print(tensor2.shape)
print(result.shape)
print(result)

torch.Size([2, 3])
torch.Size([3])
torch.Size([2])
tensor([ 50, 122])


In [27]:
# batch广播
## batch矩阵*向量
tensor1=torch.randn(10, 3, 4)
tensor2=torch.randn(4)
result=torch.matmul(tensor1, tensor2)
print(result.shape)

torch.Size([10, 3])
