In [8]:
import torch
import torch.nn.functional as F

a = torch.tensor([1.0,2.0,3.0])
print(F.softmax(a, dim=0))

tensor([0.0900, 0.2447, 0.6652])


In [5]:
import torch
import torch.nn as nn

nn_output = torch.randn(512, 10, requires_grad=True)
labels = torch.randint(0, 10, (512, ))

print(nn_output.shape)
print(labels.shape)
print(nn_output)
print(labels)

criterion = nn.CrossEntropyLoss()
loss = criterion(nn_output, labels)

print(loss.item())

torch.Size([512, 10])
torch.Size([512])
tensor([[ 1.1140, -0.4069,  1.2951,  ..., -0.2472,  0.7132, -1.3320],
        [ 0.4793, -1.5179,  0.9556,  ..., -1.8850, -1.3842, -0.2288],
        [ 1.0833,  0.7231,  0.1847,  ..., -0.4455,  0.2826, -1.8619],
        ...,
        [-0.5907,  0.5266, -0.0057,  ..., -1.0302, -1.1344, -0.1192],
        [-0.4514, -1.1279,  0.5506,  ..., -0.4486, -0.6987, -0.8888],
        [ 0.9572, -0.3570, -2.0741,  ..., -0.1473, -1.1519, -0.2951]],
       requires_grad=True)
tensor([9, 2, 5, 3, 9, 6, 9, 7, 8, 8, 5, 9, 5, 4, 6, 7, 4, 1, 3, 4, 2, 9, 4, 0,
        9, 3, 4, 8, 1, 0, 0, 5, 0, 5, 2, 0, 1, 5, 3, 9, 9, 4, 3, 4, 6, 0, 5, 1,
        5, 2, 2, 1, 2, 1, 0, 4, 2, 3, 4, 6, 1, 2, 7, 4, 3, 8, 6, 0, 0, 5, 2, 5,
        8, 9, 5, 4, 1, 9, 2, 3, 4, 9, 5, 6, 8, 5, 8, 7, 4, 5, 3, 4, 1, 3, 3, 4,
        3, 6, 0, 8, 0, 3, 7, 5, 1, 7, 4, 0, 0, 2, 3, 3, 7, 9, 5, 0, 5, 5, 4, 0,
        5, 6, 6, 7, 7, 3, 0, 1, 5, 2, 5, 6, 0, 8, 4, 3, 3, 5, 8, 6, 9, 3, 6, 5,
        7, 8, 2, 2,

In [12]:
import torch

criterion = torch.nn.CrossEntropyLoss()
input = torch.tensor([[1, 2, 3, 4, 5], [5, 6, 7, 8, 6]], dtype=torch.float)
target = torch.tensor([0, 5], dtype=torch.long)

print(input.shape)
print(target.shape)

criterion(input, target)

torch.Size([2, 5])
torch.Size([2])


tensor(3.4878)